[package]
name = "rs-example"
version = "0.1.0"
edition = "2024"

[dependencies]
async-nats = "0.43.0"
futures = "0.3.31"
tokio = { version = "1.47.1", features = ["full"] }
serde = "1.0.219"
serde_json = "1.0.143"
dirs = "6.0.0"
