package wasmcloud-tutorial:inventory-component;

world hello {
  import wasi:keyvalue/atomics@0.2.0-draft; // [!code ++]
  import wasi:keyvalue/store@0.2.0-draft; // [!code ++]
  export wasi:http/incoming-handler@0.2.2;
}
