fullnameOverride: "wasmcloud-platform"
nameOverride: "wasmcloud-platform"

nats:
  enabled: true
  podTemplate:
    merge:
      spec:
        nodeSelector:
          node-role.kubernetes.io/application-platform: "true"
  fullnameOverride: "nats"
  nameOverride: "nats"
  config:
    cluster:
      enabled: true
      replicas: 3
    leafnodes:
      enabled: true
    websocket:
      enabled: true
      port: 4223
    jetstream:
      enabled: true
      fileStore:
        pvc:
          size: 10Gi
      merge:
        domain: default

wadm:
  enabled: true
  fullnameOverride: "wadm"
  nameOverride: "wadm"
  wadm:
    image:
      tag: v0.21.0
    config:
      nats:
        server: "nats://nats-headless.wasmcloud.svc.cluster.local"
  resources: {}
  nodeSelector:
    node-role.kubernetes.io/application-platform: "true"

operator:
  enabled: true
  fullnameOverride: "wasmcloud-operator"
  nameOverride: "wasmcloud-operator"
  nodeSelector:
    node-role.kubernetes.io/application-platform: "true"

host:
  enabled: false

hostConfig:
  enabled: false
