apiVersion: k8s.wasmcloud.dev/v1alpha1
kind: WasmCloudHostConfig
metadata:
  name: wasmcloud-host
  namespace: wasmcloud
  labels:
    app.kubernetes.io/name: wasmcloud-platform
    app.kubernetes.io/instance: wasmcloud-platform
spec:
  hostReplicas: 1
  lattice: default
  version: 1.9.0
  natsAddress: nats://nats.wasmcloud.svc.cluster.local
  schedulingOptions:
    daemonset: true
    podTemplateAdditions:
      nodeSelector:
        node-role.kubernetes.io/application-platform: "true"
