package wasmcloud-tutorial:key-value-provider@0.1.0;

interface store {
    // Retrieve a value associated with a key
    get: func(key: string) -> option<string>;

    // TODO: write a function declaration called "set" which takes two string
    // arguments: "key" and "value". The function does not need to return anything
    // as it simply creates an entry in the key-value store.
    set: func(key: string, value: string);
}

// All imports and exports our provider can use / must implement.
world provider {
    export store;
}

